server:
  port: 8080

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: ordiniCqrsDb
  config:
    import:
      - optional:configserver:http://localhost:9296

springdoc:
  swagger-ui:
    path: /api-docs.html
  api-docs:
    path: /api-docs

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.web: INFO

spring.application.name: ORDINE-GET


